# -*- coding: utf-8 -*-
"""GIT_GROUP_06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0qPnYK5R_7JBWg04VQgVrgOR6PKC091
"""

from fractions import Fraction

HEX_DIGITS = "0123456789ABCDEF"


def hex_char_to_value(ch):
    # Convert a hexadecimal character to its numeric value
    if '0' <= ch <= '9':
        return ord(ch) - ord('0')
    if 'A' <= ch <= 'F':
        return ord(ch) - ord('A') + 10
    if 'a' <= ch <= 'f':
        return ord(ch) - ord('a') + 10
    return -1


def digit_char_to_value(ch):
    # Convert a decimal digit character to its numeric value
    if '0' <= ch <= '9':
        return ord(ch) - ord('0')
    return -1


def validate_decimal_input(s):
    # Validate decimal input string
    s = s.strip()

    if s == "":
        return False, "Error: input is empty."

    dot_count = 0
    sign_count = 0

    for i, ch in enumerate(s):
        if ch == '-':
            sign_count += 1
            if i != 0:
                return False, "Error: minus sign is allowed only at the beginning."
        elif ch == '.':
            dot_count += 1
            if dot_count > 1:
                return False, "Error: only one decimal point is allowed."
        elif not ('0' <= ch <= '9'):
            return False, "Error: decimal input may contain only digits, a minus sign, and a decimal point."

    if sign_count > 1:
        return False, "Error: only one minus sign is allowed."

    core = s[1:] if s[0] == '-' else s

    if core == "":
        return False, "Error: no digits were entered."

    if core == ".":
        return False, "Error: a decimal point alone is not a valid number."

    return True, None


def validate_hex_input(s):
    # Validate hexadecimal input string
    s = s.strip()

    if s == "":
        return False, "Error: input is empty."

    dot_count = 0
    sign_count = 0

    for i, ch in enumerate(s):
        if ch == '-':
            sign_count += 1
            if i != 0:
                return False, "Error: minus sign is allowed only at the beginning."
        elif ch == '.':
            dot_count += 1
            if dot_count > 1:
                return False, "Error: only one decimal point is allowed."
        else:
            if hex_char_to_value(ch) == -1:
                return False, "Error: hexadecimal input may contain only 0-9, A-F, a-f, a minus sign, and a decimal point."

    if sign_count > 1:
        return False, "Error: only one minus sign is allowed."

    core = s[1:] if s[0] == '-' else s

    if core == "":
        return False, "Error: no digits were entered."

    if core == ".":
        return False, "Error: a decimal point alone is not a valid number."

    return True, None


def parse_decimal_string_to_fraction(s):
    # Convert a valid decimal string to an exact Fraction
    s = s.strip()

    sign = 1
    if s[0] == '-':
        sign = -1
        s = s[1:]

    if '.' in s:
        integer_part, frac_part = s.split('.')
    else:
        integer_part, frac_part = s, ""

    if integer_part == "":
        integer_part = "0"

    int_value = 0
    for ch in integer_part:
        value = digit_char_to_value(ch)
        int_value = int_value * 10 + value

    frac_value = 0
    frac_len = 0
    for ch in frac_part:
        value = digit_char_to_value(ch)
        frac_value = frac_value * 10 + value
        frac_len += 1

    result = Fraction(int_value, 1)

    if frac_len > 0:
        denominator = 10 ** frac_len
        result += Fraction(frac_value, denominator)

    return sign * result


def parse_hex_string_to_fraction(s):
    # Convert a valid hexadecimal string to an exact Fraction
    s = s.strip()

    sign = 1
    if s[0] == '-':
        sign = -1
        s = s[1:]

    if '.' in s:
        integer_part, frac_part = s.split('.')
    else:
        integer_part, frac_part = s, ""

    if integer_part == "":
        integer_part = "0"

    int_value = 0
    for ch in integer_part:
        value = hex_char_to_value(ch)
        int_value = int_value * 16 + value

    frac_value = Fraction(0, 1)
    power = 16

    for ch in frac_part:
        value = hex_char_to_value(ch)
        frac_value += Fraction(value, power)
        power *= 16

    return sign * (Fraction(int_value, 1) + frac_value)


def integer_decimal_to_hex(n):
    # Convert a non-negative integer from decimal to hexadecimal
    if n == 0:
        return "0"

    result = ""
    while n > 0:
        remainder = n % 16
        result = HEX_DIGITS[remainder] + result
        n //= 16

    return result


def fraction_decimal_to_hex(frac, max_digits=5):
    # Convert the fractional part from decimal to hexadecimal
    result = ""
    count = 0

    while frac != 0 and count < max_digits:
        frac *= 16
        digit = frac.numerator // frac.denominator
        result += HEX_DIGITS[digit]
        frac -= digit
        count += 1

    was_truncated = (frac != 0)
    return result, was_truncated


def decimal_to_hex(s, max_frac_digits=5):
    # Convert a decimal string to hexadecimal string
    valid, error = validate_decimal_input(s)
    if not valid:
        return None, error, False

    value = parse_decimal_string_to_fraction(s)

    if value == 0:
        return "0", None, False

    sign = ""
    if value < 0:
        sign = "-"
        value = -value

    integer_part = value.numerator // value.denominator
    fractional_part = value - integer_part

    int_hex = integer_decimal_to_hex(integer_part)

    if fractional_part == 0:
        return sign + int_hex, None, False

    frac_hex, was_truncated = fraction_decimal_to_hex(fractional_part, max_frac_digits)

    if frac_hex == "":
        return sign + int_hex, None, was_truncated

    return sign + int_hex + "." + frac_hex, None, was_truncated


def integer_to_decimal_string(n):
    # Convert a non-negative integer to a decimal string
    if n == 0:
        return "0"

    digits = ""
    while n > 0:
        digits = chr(ord('0') + (n % 10)) + digits
        n //= 10

    return digits


def fraction_to_decimal_string(frac, max_digits=5):
    # Convert the fractional part to a decimal string
    result = ""
    count = 0

    while frac != 0 and count < max_digits:
        frac *= 10
        digit = frac.numerator // frac.denominator
        result += chr(ord('0') + digit)
        frac -= digit
        count += 1

    was_truncated = (frac != 0)
    return result, was_truncated


def hex_to_decimal(s, max_frac_digits=5):
    # Convert a hexadecimal string to a decimal string
    valid, error = validate_hex_input(s)
    if not valid:
        return None, error, False

    value = parse_hex_string_to_fraction(s)

    if value == 0:
        return "0", None, False

    sign = ""
    if value < 0:
        sign = "-"
        value = -value

    integer_part = value.numerator // value.denominator
    fractional_part = value - integer_part

    int_dec = integer_to_decimal_string(integer_part)

    if fractional_part == 0:
        return sign + int_dec, None, False

    frac_dec, was_truncated = fraction_to_decimal_string(fractional_part, max_frac_digits)

    if frac_dec == "":
        return sign + int_dec, None, was_truncated

    return sign + int_dec + "." + frac_dec, None, was_truncated


def main():
    # Maximum number of digits after the decimal point in the output
    MAX_FRAC_DIGITS = 5

    while True:
        print("\nBase 10 <-> Base 16 Conversion Calculator")
        print("1 - Convert from base 10 to base 16")
        print("2 - Convert from base 16 to base 10")
        print("3 - Exit")

        choice = input("Choose an option: ").strip()

        if choice == "1":
            user_input = input("Enter a number in base 10: ")
            result, error, was_truncated = decimal_to_hex(user_input, MAX_FRAC_DIGITS)

            if error:
                print(error)
            else:
                print("The result in base 16 is:", result)
                if was_truncated:
                    print("(For a non-terminating fractional part, up to 5 digits after the decimal point were shown.)")

        elif choice == "2":
            user_input = input("Enter a number in base 16: ")
            result, error, was_truncated = hex_to_decimal(user_input, MAX_FRAC_DIGITS)

            if error:
                print(error)
            else:
                print("The result in base 10 is:", result)
                if was_truncated:
                    print("(For a non-terminating fractional part, up to 5 digits after the decimal point were shown.)")

        elif choice == "3":
            print("Exiting the program.")
            break

        else:
            print("Error: please choose only 1, 2, or 3.")


main()