# -*- coding: utf-8 -*-
"""Group 40 Automation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZqUKOZqL_Htnf_a8Jws7fYF4QMnH6hN
"""

def decimal_to_hex(decimal_num):
    # המרה מבסיס 10 לבסיס 16
    if decimal_num == 0:
        return "0"

    is_negative = decimal_num < 0
    num = abs(decimal_num)

    hex_digits = "0123456789ABCDEF"

    # הפרדה לחלק שלם ולעשרוני
    integer_part = int(num)
    fractional_part = num - integer_part

    # המרת חלק שלם
    hex_integer = ""
    if integer_part == 0:
        hex_integer = "0"
    while integer_part > 0:
        remainder = integer_part % 16
        hex_integer = hex_digits[remainder] + hex_integer
        integer_part //= 16

    # המרת החלק העשרוני (דיוק עד 3 ספרות)
    hex_fractional = ""
    temp_frac = fractional_part
    while temp_frac > 0 and len(hex_fractional) < 3:
        temp_frac *= 16
        digit = int(temp_frac)
        hex_fractional += hex_digits[digit]
        temp_frac -= digit

    result = hex_integer
    if hex_fractional:
        result += "." + hex_fractional

    return "-" + result if is_negative else result


def hex_to_decimal(hex_str):
    #המרה מהקסדצימלי לעשרוני
    hex_str = hex_str.strip().upper()
    if not hex_str:
        raise ValueError("Null input")

    # בדיקות תקינות לסימנים (+ / -)
    if hex_str.count('-') > 1 or hex_str.count('+') > 1:
        raise ValueError("Invalid input")

    # סימן חייב להיות רק בתחילת המספר
    if ('-' in hex_str and not hex_str.startswith('-')) or \
      ('+' in hex_str and not hex_str.startswith('+')):
        raise ValueError("Invalid format")

    # לא לאפשר גם + וגם -
    if '+' in hex_str and '-' in hex_str:
        raise ValueError("Invalid format")

    is_negative = False
    if hex_str.startswith('-'):
        is_negative = True
        hex_str = hex_str[1:]
    elif hex_str.startswith('+'):
        hex_str = hex_str[1:]

    if not hex_str:
        raise ValueError("Invalid format")

    hex_digits = "0123456789ABCDEF"

    if "." in hex_str:
        parts = hex_str.split(".")
        if len(parts) > 2:
            raise ValueError("Invalid format")
        int_part_str, frac_part_str = parts
    else:
        int_part_str, frac_part_str = hex_str, ""

    # פסילה של קלט בעייתי
    if int_part_str == "" and frac_part_str == "":
        raise ValueError("Invalid format")

    decimal_value = 0.0

    # חלק שלם
    for i, digit in enumerate(reversed(int_part_str)):
        if digit not in hex_digits:
            raise ValueError(f"Invalid character: {digit}")
        decimal_value += hex_digits.index(digit) * (16 ** i)

    # החלק העשרוני
    for i, digit in enumerate(frac_part_str):
        if digit not in hex_digits:
            raise ValueError(f"Invalid character: {digit}")
        decimal_value += hex_digits.index(digit) * (16 ** -(i + 1))

    result = round(decimal_value, 3)

    if result == 0:
        return 0.0

    return -result if is_negative else result


def main():
    #לולאת המחשבון
    while True:
        print("\n" + "=" * 40)
        print("Base Conversion: Decimal ↔ Base-16")
        print("=" * 40)
        print("1. Convert Decimal to Hex")
        print("2. Convert Hex to Decimal")
        print("3. Exit")

        choice = input("Choose option(1-3): ").strip()

        if choice == '3':
            print("Goodbye!")
            break

        try:
            if choice == '1':
                raw_val = input("Enter a decimal number:").strip()
                if not raw_val:
                    raise ValueError("Null Input")
                val = float(raw_val)
                print(f"Result : {decimal_to_hex(val)}")

            elif choice == '2':
                h_str = input("Enter a hex number: ").strip()
                print(f"Result : {hex_to_decimal(h_str)}")

            else:
                print("Please enter 1, 2, or 3")

        except ValueError as e:
            print(f"Invalid input. Try again.")
        except Exception as e:
            print(f"Unexpected error: {e}")


if __name__ == "__main__":
    main()