# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NEFLVoslgT0fxyRCc5MyhFtZc39rShl
"""

# מילון שמתרגם מספרים מעל 9 לאותיות באנגלית
num_to_hex = {10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F'}

def decimal_to_hex(num):
    # טיפול במקרה של 0
    if num == 0:
        return "0"

    hex_result = ""

    # מימוש אלגוריתם המרה באמצעות חילוק חוזר ב-16 ובניית המחרוזת מהסוף להתחלה
    while num > 0:
        remainder = num % 16
        if remainder >= 10:
            # שליפת האות המתאימה מהמילון עבור שאריות הגדולות מ-9
            hex_result = num_to_hex[remainder] + hex_result
        else:
            hex_result = str(remainder) + hex_result

        # עדכון המספר על ידי חילוק בשלמים לקראת האיטרציה הבאה
        num = num // 16

    return hex_result


# לולאה שמבקשת קלט ומוודאת שהוא תקין לפני ההמרה
while True:
    user_input = input("Please enter a decimal number: ")

    # בדיקה 1: נוודא שמדובר במספר שלם (ולא שבר או טקסט)
    try:
        num = int(user_input)
    except ValueError:
        print("Error: Only integers are allowed. Please try again.")
        continue # הפקודה continue עוצרת את הסיבוב הנוכחי ומחזירה אותנו לתחילת הלולאה לניסיון נוסף

    # בדיקה 2: נוודא שהמספר חיובי
    if num < 0:
        print("Error: Only positive numbers are allowed. Please try again.")
        continue

    # הדפסת התוצאה הסופית ויציאה מסודרת מהלולאה רק לאחר קבלת קלט תקני
    print("התוצאה בהקסדצימלי:", decimal_to_hex(num))
    break # שבירת הלולאה ויציאה

# מילון שמתרגם אותיות חזרה למספרים עשרוניים
hex_to_num = {'A': 10, 'B': 11, 'C': 12, 'D': 13, 'E': 14, 'F': 15}

def hex_to_decimal(hex_str):
    # הפיכת כל המחרוזת לאותיות גדולות כדי לטפל במקרה של אותיות קטנות
    hex_str = hex_str.upper()

    decimal_result = 0
    power = 0

    # נעבור על המחרוזת מהסוף להתחלה (מימין לשמאל)
    for digit in reversed(hex_str):
        # אם התו הוא אות, ניקח את המספר המתאים מהמילון
        if digit in hex_to_num:
            value = hex_to_num[digit]
        # אם התו הוא מספר, נהפוך אותו לערך מספרי
        else:
            value = int(digit)

        # נכפיל את הערך ב-16 בחזקת המיקום שלו ונוסיף לתוצאה
        decimal_result += value * (16 ** power)

        # נקדם את החזקה ב-1 לקראת הספרה הבאה שמאלה
        power += 1

    return decimal_result

# לולאה שמבקשת קלט ומוודאת שהוא תקין לפני ההמרה
while True:
    user_input = input("Please enter a hexadecimal number: ")

    # בדיקה 1: נוודא שהמספר חיובי
    if "-" in user_input:
        print("Error: Only positive numbers are allowed. Please try again.")
        continue # מחזיר אותנו לתחילת הלולאה לניסיון נוסף

    # בדיקה 2: טיפול במקרים של תווים שאינם חוקיים בסיס 16
    try:
        result = hex_to_decimal(user_input)
    except ValueError:
        print("Error: Invalid hexadecimal format. Please try again.")
        continue

    # הדפסת התוצאה הסופית ויציאה מסודרת מהלולאה רק לאחר קבלת קלט תקני
    print("התוצאה בעשרוני:", result)
    break # שבירת הלולאה ויציאה

# -- מימוש המחשבון --
def run_tests():
    print("--- מריץ בדיקות תקינות למחשבון ---")

    # בדיקות המרה מעשרוני להקסדצימלי
    test_decimal = {0: "0", 10: "A", 15: "F", 16: "10", 255: "FF", 4095: "FFF"}
    print("\nבדיקות דצימלי -> הקסדצימלי:")
    for dec, expected in test_decimal.items():
        result = decimal_to_hex(dec)
        status = "✅" if result == expected else "❌"
        print(f"Input: {dec:4} | Expected: {expected:4} | Result: {result:4} -> {status}")

    # בדיקות המרה מהקסדצימלי לעשרוני
    test_hex = {"0": 0, "a": 10, "F": 15, "10": 16, "FF": 255, "fff": 4095}
    print("\nבדיקות הקסדצימלי -> דצימלי:")
    for h_val, expected in test_hex.items():
        result = hex_to_decimal(h_val)
        status = "✅" if result == expected else "❌"
        print(f"Input: {h_val:4} | Expected: {expected:4} | Result: {result:4} -> {status}")

run_tests()