# -*- coding: utf-8 -*-
"""BaseCalculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NEFLVoslgT0fxyRCc5MyhFtZc39rShl
"""

import time
import sys

# מילון שמתרגם מספרים מעל 9 לאותיות באנגלית
num_to_hex = {10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F'}

def decimal_to_hex(num):
    # טיפול במקרה של 0
    if num == 0:
        return "0"

    hex_result = ""
    # מימוש אלגוריתם המרה באמצעות חילוק חוזר ב-16 ובניית המחרוזת מהסוף להתחלה
    while num > 0:
        remainder = num % 16
        if remainder >= 10:
            # שליפת האות המתאימה מהמילון עבור שאריות הגדולות מ-9
            hex_result = num_to_hex[remainder] + hex_result
        else:
            hex_result = str(remainder) + hex_result
        # עדכון המספר על ידי חילוק בשלמים לקראת האיטרציה הבאה
        num = num // 16
    return hex_result

# מילון שמתרגם אותיות חזרה למספרים עשרוניים
hex_to_num = {'A': 10, 'B': 11, 'C': 12, 'D': 13, 'E': 14, 'F': 15}

def hex_to_decimal(hex_str):
    # הפיכת כל המחרוזת לאותיות גדולות כדי לטפל במקרה של אותיות קטנות
    hex_str = hex_str.upper()
    decimal_result = 0
    power = 0

    # נעבור על המחרוזת מהסוף להתחלה (מימין לשמאל)
    for digit in reversed(hex_str):
        # אם התו הוא אות, ניקח את המספר המתאים מהמילון
        if digit in hex_to_num:
            value = hex_to_num[digit]
        # אם התו הוא מספר, נהפוך אותו לערך מספרי
        else:
            value = int(digit)

        # נכפיל את הערך ב-16 בחזקת המיקום שלו ונוסיף לתוצאה
        decimal_result += value * (16 ** power)
        # נקדם את החזקה ב-1 לקראת הספרה הבאה שמאלה
        power += 1
    return decimal_result

# -- מימוש המחשבון  --
def run_calculator():
    # הודעת שגיאה לכל הקלטים הלא תקינים
    error_msg = "Error: Invalid input. Please enter a positive whole number or a valid hexadecimal value."

    while True:
        print("\n=== Number Base Calculator (Dec <-> Hex) ===")
        print("1. Decimal to Hexadecimal")
        print("2. Hexadecimal to Decimal")
        print("3. Run System Tests")
        print("4. Exit")

        choice = input("\nPlease choose an option (1-4): ")

        if choice == '1':
            while True:
                user_input = input("Enter a decimal number: ")

                # הטיפול בקלט ריק (רק לחיצה על Enter)
                if not user_input:
                    print(error_msg)
                    continue

                try:
                    num = int(user_input)
                    if num < 0:
                        print(error_msg)
                        continue
                    print(f"Result in Hexadecimal: {decimal_to_hex(num)}")
                    break # חוזר לתפריט הראשי אחרי הצלחה
                except ValueError:
                    print(error_msg)

        elif choice == '2':
            while True:
                user_input = input("Enter a hexadecimal number: ")

                # הטיפול בקלט ריק בהמרה הקסדצימלית
                if not user_input:
                    print(error_msg)
                    continue

                if "-" in user_input:
                    print(error_msg)
                    continue
                try:
                    result = hex_to_decimal(user_input)
                    print(f"Result in Decimal: {result}")
                    break
                except (ValueError, KeyError):
                    print(error_msg)

        elif choice == '3':
            run_tests()

        elif choice == '4':
            print("\n")
            shutdown_msg = "Powering down Base Calculator..."

            # יצירת אפקט הקלדה מגניב לאותיות
            for char in shutdown_msg:
                sys.stdout.write(char)
                sys.stdout.flush()
                time.sleep(0.04)  # השהיה קטנה בין כל אות

            print("\n")
            time.sleep(0.3)

            # כיבוי מערכת
            print("System Offline. GOODBYE! \n")

            time.sleep(1.5)
            break
        else:
            print("Invalid choice, please try again.")

def run_tests():
    print("\n--- Running System Validation Tests ---")
    # בדיקות המרה מעשרוני להקסדצימלי
    test_decimal = {0: "0", 10: "A", 15: "F", 16: "10", 255: "FF", 4095: "FFF"}
    print("\nTest: Decimal -> Hexadecimal:")
    for dec, expected in test_decimal.items():
        result = decimal_to_hex(dec)
        status = "✅" if result == expected else "❌"
        print(f"Input: {dec:4} | Expected: {expected:4} | Result: {result:4} -> {status}")

    # בדיקות המרה מהקסדצימלי לעשרוני
    test_hex = {"0": 0, "a": 10, "F": 15, "10": 16, "FF": 255, "fff": 4095}
    print("\nTest: Hexadecimal -> Decimal:")
    for h_val, expected in test_hex.items():
        result = hex_to_decimal(h_val)
        status = "✅" if result == expected else "❌"
        print(f"Input: {h_val:4} | Expected: {expected:4} | Result: {result:4} -> {status}")

# הפעלת התפריט הראשי
if __name__ == "__main__":
    run_calculator()