# -*- coding: utf-8 -*-
"""Ex1_Git

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BNrk4w9TSPVAODjfY3Ldb1TvtE12cwgg
"""

# Checks whether the input is valid, mode 1- decimal to hexadecimal, mode 2- hexadecimal to decimal
def is_valid_input(user_input, mode):

    # Empty input is invalid
    if user_input == "":
        return False

    # Dot at the beginning or end is invalid
    if user_input[0] == "." or user_input[-1] == ".":
        return False

    # More than one dot is invalid
    if user_input.count(".") > 1:
        return False

    if mode == 1:
        # For decimal input: only digits and dot are allowed
        for ch in user_input:
            if not (ch.isdigit() or ch == "."):
                return False

    elif mode == 2:
        # For hexadecimal input: only digits and A-F allowed
        for ch in user_input:
            if not (ch.isdigit() or ch in "ABCDEF" or ch == "."):
                return False

    else:
        return False

    return True

def hex_digit_to_decimal(ch):
    ch = ch.upper() # Convert character to uppercase to ensure uniform handling

    # If character is a digit (0-9), convert directly to integer
    if ch.isdigit():
        return int(ch)

    # Map hexadecimal letters to their decimal values
    elif ch == 'A':
        return 10
    elif ch == 'B':
        return 11
    elif ch == 'C':
        return 12
    elif ch == 'D':
        return 13
    elif ch == 'E':
        return 14
    elif ch == 'F':
        return 15

def decimal_digit_to_hex(value):
    # If value is between 0-9, return it as a string
    if 0 <= value <= 9:
        return str(value)

    # Map values 10-15 to hexadecimal characters
    elif value == 10:
        return "A"
    elif value == 11:
        return "B"
    elif value == 12:
        return "C"
    elif value == 13:
        return "D"
    elif value == 14:
        return "E"
    elif value == 15:
        return "F"


#----- Hex to Decimal------

# Converts the integer part Uses positional notation
def convert_hex_integer_part_to_decimal(integer_part):
    decimal_value = 0
    power = len(integer_part) - 1 # Highest power

    for ch in integer_part:
        digit_value = hex_digit_to_decimal(ch) # Convert hex digit to decimal value
        decimal_value += digit_value * (16 ** power) # Multiply digit by its positional value
        power -= 1

    return decimal_value

# Converts the fractional part Uses negative powers of 16
def convert_hex_fraction_part_to_decimal(fraction_part):
    decimal_value = 0
    power = -1 # Start with negative power for fractional part

    # Loop through digits after the decimal point
    for ch in fraction_part:
        digit_value = hex_digit_to_decimal(ch)
        decimal_value += digit_value * (16 ** power)
        power -= 1

    return decimal_value

#Formats decimal output to at most 'max_digits' digits after the point
def format_decimal_output(value, max_digits=6):
    value_str = str(value) # Convert number to string for manipulation

    # If there is no decimal point, return as is
    if "." not in value_str:
        return value_str

    # Split into integer and fractional parts
    integer_part, fraction_part = value_str.split(".")

    # Keep only the required number of digits after the decimal point
    fraction_part = fraction_part[:max_digits]

    # Remove unnecessary trailing zeros
    fraction_part = fraction_part.rstrip("0")

    # If nothing remains after removing zeros, return only integer part
    if fraction_part == "":
        return integer_part

    return integer_part + "." + fraction_part

def convert_hex_to_decimal(hex_number):
    # Check if number contains a decimal point and split into integer and fractional parts
    if "." in hex_number:
        parts = hex_number.split(".")
        integer_part = parts[0]
        fraction_part = parts[1]

        # Convert each part separately
        integer_value = convert_hex_integer_part_to_decimal(integer_part)
        fraction_value = convert_hex_fraction_part_to_decimal(fraction_part)

        result = integer_value + fraction_value
        # limit digits after decimal point
        return format_decimal_output(result, 6)

    else:
        # If no fractional part, convert only integer part
        return str(convert_hex_integer_part_to_decimal(hex_number))


#----- Decimal to Hex------

# Converts integer part from decimal to hexadecimal using repeated division
def convert_decimal_integer_part_to_hex(integer_part):
    integer_part = int(integer_part)

    # Special case: if number is 0
    if integer_part == 0:
        return "0"

    hex_result = ""

    # Repeat until number becomes 0
    while integer_part > 0:
        remainder = integer_part % 16 # Get remainder
        hex_digit = decimal_digit_to_hex(remainder) # Convert to hex character

        # Add digit to the left
        hex_result = hex_digit + hex_result

        integer_part = integer_part // 16 # Reduce number

    return hex_result

#Converts fractional part from decimal to hexadecimal using repeated multiplication
def convert_decimal_fraction_part_to_hex(fraction_part, max_digits=6):
    # Convert string to decimal fraction
    fraction_value = float("0." + fraction_part)
    hex_result = ""
    count = 0

    # Continue while fraction exists and limit not reached
    while fraction_value > 0 and count < max_digits:
        fraction_value *= 16 # Multiply by base
        integer_digit = int(fraction_value) # Extract integer part
        hex_result += decimal_digit_to_hex(integer_digit)
        fraction_value -= integer_digit # Keep only fractional remainder
        count += 1

    return hex_result

def convert_decimal_to_hex(decimal_number):
    # Check if number has fractional part
    if "." in decimal_number:
        parts = decimal_number.split(".")
        integer_part = parts[0]
        fraction_part = parts[1]

        # Convert each part separately
        integer_result = convert_decimal_integer_part_to_hex(integer_part)
        fraction_result = convert_decimal_fraction_part_to_hex(fraction_part)

        # If no fractional result, return only integer part
        if fraction_result == "":
            return integer_result
        else:
            return integer_result + "." + fraction_result

    else:
        return convert_decimal_integer_part_to_hex(decimal_number)

#----- User interaction------
def decimal_to_hex():
    while True:
        user_input = input("Enter a decimal number: ")

        # Validate input before processing
        if is_valid_input(user_input, 1):
            result = convert_decimal_to_hex(user_input)
            print("The hexadecimal value is:", result)
            break
        else:
            print("Invalid input. Please try again")


def hex_to_decimal():
    while True:
        user_input = input("Enter a hexadecimal number: ")

        # Validate input
        if is_valid_input(user_input,2):
            result = convert_hex_to_decimal(user_input)
            print("The decimal value is:", result)
            break
        else:
            print("Invalid input. Please try again")


def main():
    while True:
        print("\nChoose an option:")
        print("1- Convert from decimal to hexadecimal")
        print("2- Convert from hexadecimal to decimal")
        print("3- Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            decimal_to_hex()
        elif choice == "2":
            hex_to_decimal()
        elif choice == "3":
            print("Program ended")
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3")


main()

# Tests for hex to decimal

print("Test 1:", convert_hex_to_decimal("1A"), "Expected: 26")
print("Test 2:", convert_hex_to_decimal("10"), "Expected: 16")
print("Test 3:", convert_hex_to_decimal("FF"), "Expected: 255")
print("Test 4:", convert_hex_to_decimal("A"), "Expected: 10")
print("Test 5:", convert_hex_to_decimal("0"), "Expected: 0")


# Tests for decimal to hex
print("Test 6:", convert_decimal_to_hex("26"), "Expected: 1A")
print("Test 7:", convert_decimal_to_hex("16"), "Expected: 10")
print("Test 8:", convert_decimal_to_hex("255"), "Expected: FF")
print("Test 9:", convert_decimal_to_hex("10"), "Expected: A")
print("Test 10:", convert_decimal_to_hex("0"), "Expected: 0")

# Tests for valid decimal input (mode=1)
print("Test 11:", is_valid_input("123", 1), "Expected: True")
print("Test 12:", is_valid_input("12.3", 1), "Expected: True")
print("Test 13:", is_valid_input("0", 1), "Expected: True")
print("Test 14:", is_valid_input("0.5", 1), "Expected: True")
print("Test 15:", is_valid_input(".123", 1), "Expected: False")

# Tests for valid hexadecimal input (mode=2)
print("Test 16:", is_valid_input("1A", 2), "Expected: True")
print("Test 17:", is_valid_input("A.F", 2), "Expected: True")
print("Test 18:", is_valid_input("FF", 2), "Expected: True")
print("Test 19:", is_valid_input("0", 2), "Expected: True")
print("Test 20:", is_valid_input("A..3", 2), "Expected: False")