# -*- coding: utf-8 -*-
"""Exc1_Group10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhP4wZsUP5PKA3XgLn3eexdnqRcpyYlG
"""

def decimal_to_hex(number, precision=8):
    hex_digits = "0123456789ABCDEF"

    # Handle the sign
    sign = ""
    if number < 0:
        sign = "-"
        number = -number

    # Separate into integer part and fractional part
    integer_part = int(number)
    fractional_part = number - integer_part

    #  Convert the integer part
    if integer_part == 0:
        integer_hex = "0"
    else:
        integer_hex = ""
        while integer_part > 0:
            remainder = integer_part % 16
            integer_hex = hex_digits[remainder] + integer_hex
            integer_part //= 16

    #  Convert the fractional part
    if fractional_part == 0:
        return sign + integer_hex

    fractional_hex = ""
    count = 0

    while fractional_part > 0 and count < precision:
        fractional_part *= 16
        digit = int(fractional_part)
        fractional_hex += hex_digits[digit]
        fractional_part -= digit
        count += 1

    return sign + integer_hex + "." + fractional_hex


def convert_decimal_input_to_hex(user_input, precision=8):
    user_input = user_input.strip()

    if user_input == "":
        return "Error: empty input is not valid."

    # Check that there is at most one decimal point
    if user_input.count(".") > 1:
        return "Error: invalid decimal number format."

    # Check that the minus sign, if present, appears only at the beginning
    if user_input.count("-") > 1 or ("-" in user_input and user_input[0] != "-"):
        return "Error: invalid negative number format."

    # Check for invalid inputs like "-", ".", or "-."
    if user_input in {"-", ".", "-."}:
        return "Error: invalid numeric input."

    # Check that all characters are valid
    allowed_chars = "0123456789.-"
    for ch in user_input:
        if ch not in allowed_chars:
            return "Error: input must be a decimal number only."

    # Attempt to convert to a number
    try:
        number = float(user_input)
    except ValueError:
        return "Error: invalid numeric input."

    # Call the conversion function
    return decimal_to_hex(number, precision)

print(convert_decimal_input_to_hex("58"))       # 3A
print(convert_decimal_input_to_hex("10.625"))   # A.A
print(convert_decimal_input_to_hex("-15.25"))   # -F.4
print(convert_decimal_input_to_hex("hello"))    # Error
print(convert_decimal_input_to_hex("12..3"))    # Error
print(convert_decimal_input_to_hex(""))         # Error
print(convert_decimal_input_to_hex("-."))       # Error
print(convert_decimal_input_to_hex("12-3"))     # Error
print(convert_decimal_input_to_hex("3a"))
print(convert_decimal_input_to_hex("-10.625"))
print(convert_decimal_input_to_hex("000058"))
print(convert_decimal_input_to_hex("."))

def hex_char_to_value(ch):
    hex_digits = "0123456789ABCDEF"
    return hex_digits.index(ch)


def hex_to_decimal(hex_string):
    hex_string = hex_string.strip().upper()

    if hex_string == "":
        return "Error: empty input is not valid."

    # Handle the sign
    sign = 1
    if hex_string[0] == "-":
        sign = -1
        hex_string = hex_string[1:]

    # Basic validations after removing the sign
    if hex_string == "":
        return "Error: invalid hexadecimal input."

    if hex_string.count(".") > 1:
        return "Error: invalid hexadecimal format."

    if hex_string in {".", "-."}:
        return "Error: invalid hexadecimal input."

    # Check that all characters are valid
    allowed_chars = "0123456789ABCDEF."
    for ch in hex_string:
        if ch not in allowed_chars:
            return "Error: input must be a hexadecimal number only."

    # Split into integer and fractional parts
    parts = hex_string.split(".")
    integer_part = parts[0]
    fractional_part = parts[1] if len(parts) == 2 else ""

    # If nothing appears before the decimal point, treat it as 0
    if integer_part == "":
        integer_part = "0"

    decimal_value = 0

    # Convert the integer part
    power = 0
    for ch in reversed(integer_part):
        value = hex_char_to_value(ch)
        decimal_value += value * (16 ** power)
        power += 1

    # Convert the fractional part
    power = -1
    for ch in fractional_part:
        value = hex_char_to_value(ch)
        decimal_value += value * (16 ** power)
        power -= 1

    return sign * decimal_value

print(hex_to_decimal("3A"))      # 58
print(hex_to_decimal("1A.8"))    # 26.5
print(hex_to_decimal("A.a"))     # 10.625
print(hex_to_decimal("-F.4"))    # -15.25
print(hex_to_decimal("0.8"))     # 0.5
print(hex_to_decimal("ff"))      # 255
print(hex_to_decimal("hello"))   # Error
print(hex_to_decimal("1G"))      # Error
print(hex_to_decimal(""))        # Error
print(hex_to_decimal("A..5"))    # Error

def main():
    while True:
        print("\n--- Base Conversion Calculator ---")
        print("1. Convert Decimal (10) to Hexadecimal (16)")
        print("2. Convert Hexadecimal (16) to Decimal (10)")
        print("3. Exit")

        choice = input("Choose an option (1/2/3): ").strip()

        if choice == "1":
            decimal_input = input("Enter a decimal number (negatives and fractions allowed): ").strip()

            # Call the wrapper function that validates and converts
            result = convert_decimal_input_to_hex(decimal_input)

            # Check if we received an error message or a valid result
            if isinstance(result, str) and result.startswith("Error"):
                print(result)
            else:
                print(f"The hexadecimal representation of {decimal_input} is: {result}")

        elif choice == "2":
            hex_input = input("Enter a hexadecimal number (negatives and fractions allowed): ").strip()

            # Call the wrapper function that validates and converts
            result = hex_to_decimal(hex_input)

            # Check if we received an error message or a valid result
            if isinstance(result, str) and result.startswith("Error"):
                print(result)
            else:
                print(f"The decimal representation of {hex_input.upper()} is: {result}")

        elif choice == "3":
            print("Exiting the program. Good luck with your submission!")
            break

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

# This ensures the script runs only when executed directly
if __name__ == "__main__":
    main()